export function createServerTestingExports({
  config,
  acquireCodexAccountLease,
  applyCodexInvalidatedAccountState,
  isCodexAccountLeased,
  isCodexPoolRetryEnabled,
  pickCodexAccountCandidates,
  removeCodexPoolAccountFromStore,
  isCodexTokenInvalidatedError,
  startExpiredAccountCleanupTimer,
  stopExpiredAccountCleanupTimer,
  getExpiredAccountCleanupTimer,
  ensureCodexOAuthCallbackServer,
  stopCodexOAuthCallbackServer,
  getCodexOAuthCallbackServer,
  getCloudflaredRuntime,
  stopCloudflaredTunnel,
  getCodexOAuthStore,
  setCodexOAuthStore,
  ensureCodexOAuthStoreShape,
  buildOfficialCodexModelCandidateIds,
  fetchCodexModelIdsForAccountToken,
  getExecutableModelCandidateIds,
  resolveCodexPreheatModelSelection,
  incrementPreheatHistoryCount,
  normalizeTokenRefreshResultExpiresAt,
  normalizeCodexServiceTier,
  refreshCodexUsageSnapshotInStore,
  normalizeCodexResponsesRequestBody,
  normalizeChatCompletionsRequestBody,
  parseResponsesResultFromSse,
  estimateOpenAIChatCompletionTokens,
  runDirectChatCompletionTest,
  refreshOpenAICodexToken,
  exchangeCodeForToken,
  parseInteger,
  parsePositiveInteger,
  anthropicLocalCompatHelpers,
  buildCodexResponsesRequestBody,
  handleGeminiNativeProxy,
  handleAnthropicNativeProxy,
  handleGeminiProtocol,
  handleAnthropicProtocol,
  mapHttpStatusToGeminiStatus,
  mapHttpStatusToAnthropicErrorType,
  resolveCompatErrorStatusCode,
  isUnsupportedMaxOutputTokensError,
  readCachedCodexModelIdsForAccount
}) {
  return {
    config,
    acquireCodexAccountLease,
    applyCodexInvalidatedAccountState,
    isCodexAccountLeased,
    isCodexPoolRetryEnabled,
    pickCodexAccountCandidates,
    removeCodexPoolAccountFromStore,
    isCodexTokenInvalidatedError,
    startExpiredAccountCleanupTimer,
    stopExpiredAccountCleanupTimer,
    getExpiredAccountCleanupTimer,
    ensureCodexOAuthCallbackServer,
    stopCodexOAuthCallbackServer,
    getCodexOAuthCallbackServer,
    getCloudflaredRuntime,
    stopCloudflaredTunnel,
    getCodexOAuthStore,
    setCodexOAuthStore,
    ensureCodexOAuthStoreShape,
    buildOfficialCodexModelCandidateIds,
    fetchCodexModelIdsForAccountToken,
    getExecutableModelCandidateIds,
    resolveCodexPreheatModelSelection,
    incrementPreheatHistoryCount,
    normalizeTokenRefreshResultExpiresAt,
    normalizeCodexServiceTier,
    refreshCodexUsageSnapshotInStore,
    normalizeCodexResponsesRequestBody,
    normalizeChatCompletionsRequestBody,
    parseResponsesResultFromSse,
    estimateOpenAIChatCompletionTokens,
    runDirectChatCompletionTest,
    refreshOpenAICodexToken,
    exchangeCodeForToken,
    parseInteger,
    parsePositiveInteger,
    normalizeCherryAnthropicAgentOriginalUrl: anthropicLocalCompatHelpers.normalizeCherryAnthropicAgentOriginalUrl,
    parseAnthropicNativeBody: anthropicLocalCompatHelpers.parseAnthropicNativeBody,
    normalizeAnthropicNativeTools: anthropicLocalCompatHelpers.normalizeAnthropicNativeTools,
    normalizeAnthropicNativeToolChoice: anthropicLocalCompatHelpers.normalizeAnthropicNativeToolChoice,
    normalizeAnthropicNativeExecutionConfig: anthropicLocalCompatHelpers.normalizeAnthropicNativeExecutionConfig,
    resolveAnthropicNativeReasoningSummary: anthropicLocalCompatHelpers.resolveAnthropicNativeReasoningSummary,
    normalizeAnthropicToolUseInput: anthropicLocalCompatHelpers.normalizeAnthropicToolUseInput,
    toResponsesInputFromAnthropicMessages: anthropicLocalCompatHelpers.toResponsesInputFromAnthropicMessages,
    planAnthropicFunctionCallEmission: anthropicLocalCompatHelpers.planAnthropicFunctionCallEmission,
    rememberAnthropicPendingToolBatch: anthropicLocalCompatHelpers.rememberAnthropicPendingToolBatch,
    maybeBuildQueuedAnthropicToolMessage: anthropicLocalCompatHelpers.maybeBuildQueuedAnthropicToolMessage,
    clearAnthropicPendingToolBatches: anthropicLocalCompatHelpers.clearAnthropicPendingToolBatches,
    buildAnthropicMessageFromResponsesResponse: anthropicLocalCompatHelpers.buildAnthropicMessageFromResponsesResponse,
    renderAnthropicMessageSseEvents: anthropicLocalCompatHelpers.renderAnthropicMessageSseEvents,
    estimateAnthropicCountTokens: anthropicLocalCompatHelpers.estimateAnthropicCountTokens,
    buildCodexResponsesRequestBody,
    handleGeminiNativeProxy,
    handleAnthropicNativeProxy,
    handleGeminiProtocol,
    handleAnthropicProtocol,
    mapHttpStatusToGeminiStatus,
    mapHttpStatusToAnthropicErrorType,
    resolveCompatErrorStatusCode,
    isUnsupportedMaxOutputTokensError,
    readCachedCodexModelIdsForAccount
  };
}
